version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.9
    working_directory: ~/add_ssh_users
    steps:
      - checkout
      - run: pip install --user -r ./.circleci/requirements.txt
      - run: ansible-lint add_ssh_users.yml -c .circleci/.ansible-lint
